### ISSUE TITLE
 Error:Type with name "_tag" does not exists

### ISSUE THREAD

**Issue by KarolNet** [flotiq/gatsby-source-flotiq#56]
Hi,
In the new Flotiq version, we added relation to type _tag in _media.
So builds projects who included "gatsby-source-flotiq" ended fail with error:

` Error:Type with name "_tag" does not exists `

Fast solution for this error is added _tag type to "gatsby-source-flotiq" configuration:

 `includeTypes: ['_media', '_tag']` 

like this: https://github.com/flotiq/gatsby-starter-boilerplate/commit/54b4dbae00580789ec0d78e8911cd497c35fe869

**Comment by trzcina** [comment]
We've fixed it globally - if a type is not listed in `includeTypes`, it is fetched as standard, not resolved, DataSource object containing dataUrl and type property (check the hydration disabled example here https://flotiq.com/docs/API/content-type/listing-co/#hydrating-objects)
